development:
  adapter: postgresql
  encoding: unicode
  database: glossarium_development
  pool: 5
  username: glossarium
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: glossarium_test
  pool: 5
  username: glossarium
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: glossarium_production
  pool: 5
  username: glossarium
  password:
